name: oxford_dictionary
description: Oxford Dictionary Dart client. Use it to get word definitions, pronunciations and examples.
version: 1.0.1
homepage: https://github.com/rIIh

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  http: ^0.12.2
  chopper: ^3.0.6
  json_annotation: ^3.1.0
  stash: ^1.0.2

dev_dependencies:
  effective_dart: ^1.2.4
  build_runner: ^1.10.4
  json_serializable: ^3.5.0
  chopper_generator: ^3.0.6
  mockito: ^4.1.3
  test: ^1.15.4
