name: oxford_dictionary
description: Oxford Dictionary Dart client. Use it to get word definitions,
  pronunciations and examples.
version: 2.0.2
homepage: https://github.com/rIIh

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  chopper: ^4.0.0
  http: ^0.13.0
  json_annotation: ^4.0.0
  stash: ^2.0.0

dev_dependencies:
  build_runner: ^2.0.0
  chopper_generator: ^4.0.0
  effective_dart: ^1.3.0
  json_serializable: ^4.1.0
  mockito: ^5.0.0
  test: ^1.17.0